name: proteinttt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy
  - pandas
  - biopython
  - tqdm
  - pyyaml
  - requests
  - click
  - matplotlib
  - pip
  - pip:
    - torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchvision==0.16.2+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchaudio==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121

    - "fair-esm[esmfold]"
    - pytorch-lightning==1.8.4
    - torchmetrics==0.10.3
    - wandb==0.21.0
    - tensorboardX==2.6.4
    - einops==0.8.1
    - omegaconf==2.3.0
    - biotite==0.40.0
    - huggingface-hub==0.16.4
    - fire==0.7.0
    - transformers==4.30.0
    - diffusers==0.15.0
    - ml-collections
    - dm-tree
    - "setuptools<70"
